### ISSUE TITLE
readme: recommend enabling envfs service

### ISSUE THREAD

**Issue by PowerUser64** [Mic92/envfs#104]
Since envfs is in nixpkgs now (congrats!), it would probably be good to change the recommend installation method in the readme to be installing from nixpkgs by enabling the service. It's only available in nixos unstable, so it's still worth mentioning other methods, but I'm sure many people would appreciate knowing there's a service too.

**Comment by Mic92** [comment]
Agreed. I still have on my agenda to write a blogpost similar to https://blog.thalheim.io/2022/12/31/nix-ld-a-clean-solution-for-issues-with-pre-compiled-executables-on-nixos/ for envfs, but than also the manual should mention both.

**Comment by PowerUser64** [comment]
I just remembered this issue. Now that v23.05 is stable (putting envfs in the stable release channel), it should be safe to change this section of the readme.
