### ISSUE TITLE
`services.envfs.enable = true;` breaks nixos-install

### ISSUE THREAD

**Issue by peterwaller-arm** [Mic92/envfs#111]
If I enable envfs (either via the nixos configuration, or via flake as per the current instructions in the README), right at the end of the installation process while installing the bootloader I get:
```
updating GRUB 2 menu...
Can't exec "/bin/sh": No such file or directory at /nix/store/kdlihrdxakv00jm07vqix8svk2wssdcq-install-grub.pl line 51.
Failed to execute: /nix/store/56kvc3cxxwcxy84rfbgmvafnhvibz9md-util-linux-2.38.1-bin/bin/blkid -o export /dev/nvme1n1p2
```

This does not appear to happen if I disable envfs, starting with a fresh machine each time.

**Comment by lilyinstarlight** [comment]
I've encountered similar problems of stdenv script bins relying on the existence of `/bin/sh` like here

I don't use GRUB so I don't have this issue, but other similar issues is why I have an activation script in my config that copies the envfs fallback bins to the underlying filesystem too on activation: https://github.com/lilyinstarlight/foosteros/blob/a66281089f11b0fd459e7c50c8e26282c23ebc51/config/alien.nix#L4-L13

**Comment by lilyinstarlight** [comment]
> envfs is not mounted during the installation right?

It's not, but it still disables the activation scripts that would add those file, I think?

**Comment by Mic92** [comment]
Yes. That it disables it.

**Comment by lilyinstarlight** [comment]
> Yes. That it disables it. Maybe it needs to be mounted in activation phase as well...

Either that or coming up with a solution to make sure the bins exist as normal if it's not mounted (e.g. making those activation scripts conditional on `mountpoint -q /bin` rather than uncondtionally disabled -- Unfortunately I'm not sure how to get at the original activation script when overriding with `mkForce` like that, though)

**Comment by Mic92** [comment]
This is a workaround for now: https://github.com/NixOS/nixpkgs/pull/223418

**Comment by Mic92** [comment]
So nixpkgs-unstable should no longer fail.

**Comment by Mic92** [comment]
Hopefully no longer an issue in all NixOS versions?
