### ISSUE TITLE
Could this project make the default PATH usable?

### ISSUE THREAD

**Issue by purkhusid** [Mic92/envfs#139]
I'm curious if this project could somehow make the default PATH work like it does on FHS systems? My exact issue is that I'm using Bazel to build projects and Bazel executes commands where the PATH is not set. 

On a normal FHS system the default PATH would be used which would be something like `/usr/local/bin:/usr/bin` but on NixOS the default PATH is set to `/no-such-path`.

If this does not fit into the scope of this project then feel free to close the issue!

**Comment by Mic92** [comment]
If only the default PATH is set than the filesystem will not work because it relies on PATH to point to something else but itself to find binaries which are than returned as symlinks.

**Comment by purkhusid** [comment]
Do you have any ideas how one might replace the default PATH that is set in `bash` and `bashInteractive` ?

**Comment by Mic92** [comment]
This bash should do the job: `(bash.override { forFHSEnv = true; })`

**Comment by Mic92** [comment]
Or you can use overrideAttrs to set some other value: https://github.com/NixOS/nixpkgs/blob/c13348cde75b1aff57d6fd32277a74296a115320/pkgs/shells/bash/5.nix#L47
