### ISSUE TITLE
Loading module via flake duplicates fallback-path and doesn't work as expected

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/envfs#149]
I added the module as described [here](https://github.com/Mic92/envfs#flakes) to my flake and the fallback-path mount option is now duplicated.

```
none /usr/bin envfs fallback-path=/nix/store/hiyvx1mfzah7lqr8bphyys7n08j36z8x-fallback-path,nofail,bind-mount=/bin,fallback-path=/nix/store/jzdimbli3q7fba1izbxnrpn3qq39s05x-fallback-path,nofail 0 0
```

Disabling it via ``disabledModules = [ "tasks/filesystems/envfs.nix" ];`` works but then the options defined in nixos (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/filesystems/envfs.nix#L25-L50) are missing and I can no longer use envfs in wsl.

**Comment by Mic92** [comment]
Have you still enabled the other module?

**Comment by SuperSandro2000** [comment]
> Have you still enabled the other module?

I need to, otherwise options I am using for NixOS-WSL are missing.

**Comment by Mic92** [comment]
In that case you might be better off just copy the module and change it.
