### ISSUE TITLE
Breaks many, many services 

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/envfs#151]
I've tried the latest update and it broke ssh, Getty, phpfpm. Since I didn't have any way to access the machine in that state I couldn't collect any logs. journalctl -b -1 also didn't contain anything I could find at least closely related to this. I have no real idea how to help to fix this. I think running nixos VM tests with envfs enabled could help making sure less regressions like this happen.

**Comment by Mic92** [comment]
The problem happend because nixos-rebuild switch didn't re-start envfs after the upgrade.
It's addressed here: https://github.com/Mic92/envfs/pull/152

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/297142

**Comment by Mic92** [comment]
Fixed.
