### ISSUE TITLE
`/usr/bin` & `/bin` empty after mount

### ISSUE THREAD

**Issue by suimong** [Mic92/envfs#162]
I enabled the `service.envfs` on my NixOS 24.05, and while `mount | grep envfs` shows that `/usr/bin` and `/bin` is mounted properly, the two directories are just empty. Am I doing something wrong?

**Comment by SuperSandro2000** [comment]
They look like they are empty but if you run /bin/bash or so some program that should exist, it should be there anyway.

**Comment by Mic92** [comment]
But mount should still show envfs as a mountpoint.

**Comment by Mic92** [comment]
What happens if you manually run mount /usr/bin?

**Comment by suimong** [comment]
> They look like they are empty but if you run /bin/bash or so some program that should exist, it should be there anyway.

Ah silly of me... Thanks for explaining.

**Comment by suimong** [comment]
> But mount should still show envfs as a mountpoint.

`mount` does show two envfs mountpoints: `/usr/bin` and `/bin`, so I guess everything is just in order. Thanks.
